### ISSUE TITLE
UPDATED: HELP!!! How to render child components from parent component.

### ISSUE THREAD

**Issue by anantthebiker** [spotify/HubFramework#154]
# My own implementation to this Q is under the "UPDATE" below, Kindly share your opinion on that:
Hi! @JohnSundell 
1) I am having a JSON file with "children:" key & child component. 
2) I have read all the required docs. on adding child components & went through the "protocol HUBComponentChildDelegate" as well which houses all the methods for operations on Child Components.
3) I have a parent component file which adhere to: "HUBComponentWithChildren" & a "childDelegate" reference as well.

But I am quite confused as to in which method of the "HubComponent" do I call the methods of "childDelegate" & how. In the demo app I couldn't find an example on it. 
Could someone please share an example or any help in this regard. 
It might be quite naive but am new to this framework & swift in general. 
Thanks.
Anant

# UPDATE: 
Due to lack of any example available, I did some experimentation on how to add Child components to the parent one, here is what I have done, kindly share your wisdom as to is it the best way to render child components:
<img width="657" alt="screen shot 2016-11-16 at 1 08 22 pm" src="https://cloud.githubusercontent.com/assets/8290135/20338556/ccee8028-abfd-11e6-8a87-cace889806d0.png">
^^ Parent Component : type:"UIView" housing a child component type:"row"

Then in the "cities:plainView" component:(Which actually is nothing but an empty View with: 

> CGSize(width: containerViewSize.width, height: 300) 
)

So inside the 

> configureView(with model: HUBComponentModel, containerViewSize: CGSize) 
I added: 

<img width="785" alt="screen shot 2016-11-16 at 1 19 02 pm" src="https://cloud.githubusercontent.com/assets/8290135/20338840/53ef4962-abff-11e6-982c-9a1c84ea7841.png">

So by manually adding child's view as a Subview of the Parent's View, only then it is that I am seeing the child getting appeared.

So here are some of doubts that I still have:
1) Is this the correct & best approach to render a child component within the parent's? 
2) Does: ` public func component(_ component: HUBComponentWithChildren, childComponentFor childComponentModel: HUBComponentModel) -> HUBComponent` not automatically showcase the child'sview inside of a Paren't view apart from instantiating the child element.
3) Some other best practices for child component rendering, kindly share them.
@JohnSundell @rastersize @Goos @diegc 
Thanks,
Anant 
https://twitter.com/anantthebiker

**Comment by JohnSundell** [comment]
@anantthebiker Hey! So parent components are responsible for managing & laying out their children, just like a superview is responsible for its subviews in UIKit. We don't want to make any assumptions in the framework how you want to use your child component (for example, you might want to put it in a collection view cell, or in a container view, rather than adding it to the parent component's view directly). We should probably document this behavior a bit better 😄

For an example on how to use child components, see the [Carousel component in the demo app](https://github.com/spotify/HubFramework/blob/master/demo/sources/CarouselComponent.swift).

Notifying the framework about when a component will appear/disappear enables the framework to forward those events to `HUBViewControllerDelegate`.

**Comment by anantthebiker** [comment]
Thanks! @JohnSundell apparently I was looking @ the old Demo app :D

**Comment by JohnSundell** [comment]
@anantthebiker Ah, no worries. Can we close this issue?

**Comment by anantthebiker** [comment]
Yeah why not, anyway I have Twitter, Slack to reach out to you until Feb :bowtie:

**Comment by JohnSundell** [comment]
@anantthebiker I'll still be on Twitter and Slack and here after February too you know 😉
