### ISSUE TITLE
Convenience initializer for the HUBManager

### ISSUE THREAD

**Issue by pepibumur** [spotify/HubFramework#161]
### What?
When I tried to instantiate the `HUBManager` in my project I had to look into the implementation of the `ComponentFallbackHandler` and the `ComponentLayoutManager` and literally copied and paste it. I don't know how other projects using the library did it but I think it would be very handy to provide basic implementations for these two protocols, `HUBComponentFallbackHandler`, `HUBComponentLayoutManager`.

That way you could easily instantiate the `HUBManager` with:

```swift
let manager = HUBManager()
```
And only provide a different implementation if you need it.

**Comment by JohnSundell** [comment]
Awesome idea! 🚀

I totally agree that the framework is currently a bit too heavy to setup. Would be very nice with a convenience initializer for `HUBManager`. However, we'd probably need to make it have at least a few arguments, since we can't make too many assumptions i the default implementations of `HUBComponentFallbackHandler` and `HUBComponentLayoutManager`. There are two pieces of info that I think we'll need the API user to supply no matter what:

- A `component category : name` map for fallbacks (the framework cannot know what components a given app has support for, and the fallback handler always needs to return a component).
- What margin to use for the layout manager. (similar to [this constant in the demo app](https://github.com/spotify/HubFramework/blob/master/demo/sources/ComponentLayoutManager.swift#L28)).

So the signature for the convenience initializer could be:

```swift
let manager = HUBManager(
    componentMargin: 15,
    fallbackComponentNames: [
        .row: "row",
        .card: "card"
   ]
)
```

I guess another option would be to force an app using the Hub Framework to always have certain components available (like "row", "card", etc), but that feels a bit... aggressive 😅

**Comment by pepibumur** [comment]
That's a good idea, and the initializer could create the default `HUBComponentFallbackHandler` and `HUBComponentLayoutManager` with the provided attributes.

**Comment by JohnSundell** [comment]
Exactly 👍

**Comment by aliak00** [comment]
> There are two pieces of info that I think we'll need the API user to supply no matter what:

How would you feel about providing (arbitrary) sensible defaults for those two things? So if a user instantiated a `HUBManager` it's fallback could return `HUBMissingComponent` (or `HUBEmptyComponent` for eg) that is simply a fullwidth row with a text label, or a table cell or something. Can also maybe add a color to background to make it obviously stick out if. 

The margin can also sensibly be set to 10 for eg no?

The color thing is assuming that getting the fallback to provide a component for the app sounds like it might be an error usually?

**Comment by JohnSundell** [comment]
@aliak00 @pepibumur I created this PR: https://github.com/spotify/HubFramework/pull/193 to deal with this issue. IMO, it strikes the balance between powerful defaults and not being too ambigious. Let me know what you think 😄

**Comment by pepibumur** [comment]
I went through it and it looks fine 👍 . Great job @JohnSundell

**Comment by aliak00** [comment]
Looks good @JohnSundell 👍 I saw the comments as well, I'd probably agree with adding it as an extension just for code separation purposes but not as a creationary class type method because it feels like what an initializer is supposed to do. But no strong opinions here :)
