### ISSUE TITLE
Allow operations to be added dynamically to the content loading chain

### ISSUE THREAD

**Issue by CalvHobbes** [spotify/HubFramework#276]
This is a feature request to allow the ability for either an OperationFactory , or if that's not viable, allow a HubOperation to add additional operations to the existing chain. Currently, when the operation factory is invoked, it has to know the list of operations to return. My use case is where I need to query a service to figure out which components (and therefore which HubOperation(s)) need to be on the page. Since the operation factory has to return immediately, I can envisage a scenario where it returns a single "DynamicHubOperation" that queries my service, and then invokes something akin to the current _contentOperationWrapperRequiresRescheduling_ method, say, _contentOperationRequiresAdditionalOperations(self,newoperations:[HubOperation])_ or something like that. The delegate (most likely the _HubViewModelLoaderImplementation_) then rearranges its _contentOperations_ array (appends the new operations right after the current one, thus changing index of the subsequent operations), and then maybe invokes _scheduleContentOperationsFromIndex_ to reload the chain from the current operation (or the next one in the chain), thus triggering the newly added operations now. 

@JohnSundell - You'd also suggested the possibility of explicitly instantiating the required operations and then invoking the perform method on them, but as we discussed, those operations don't become a part of the chain and thus will have to always be "manually" invoked if any operation in the chain requires rescheduling. We'd also need to ensure these explicitly instantiated operations  are in memory and can act as actionobservers etc. 
@rastersize , @cerihughes, @JohnSundell  suggested I tag you on this as well. 

Thanks!

**Comment by CalvHobbes** [comment]
I have a preliminary implementation of this [here](https://github.com/CalvHobbes/HubFramework/tree/dynamicoperations)

**Comment by mhallendal** [comment]
Sorry for late reply. This sounds like something that is beyond the scope of content operations and view model loader. 

A simpler solution (both from implementation and reasoning in my opinion) could be to simply add all the potential content operations to the list from the start. Then instead of the initial content operation adding/removing content operations, it sets custom data on the view model builder that is read by the other content operations to figure out if they should do any work or simply return finished.

Something like:
`
  A -> B -> C -> D
`

`A` figures out which of `B`, `C` and `D` should be inserted in the page. `A` uses `[viewModelBuilder setCustomDataValue:forKey:]` to set the data needed by `B`, `C` and `D` to figure out what to do.

If `A` set the data that indicates to `B` to execute, `B` does its work and adds it's components to the view model builder. `C` and `D` just simply calls `contentOperationDidFinish:`.

**Comment by CalvHobbes** [comment]
Hi @mhallendal , thank you for your response. While that would certainly make things easier, my use case is such that I have no idea about either the order, or the number of times the same operation may need to occur in the chain. For instance, the author of the feature (page in my case) may decide they want a Banner component in the 1st and 4th positions etc. The above solution ties me down to a sequence of operations and restricts to just one operation per type. I do realize though, that HubFramework wasn't built with this use case in mind. The gist of it is that the page "template" is define outside the app and can change.

**Comment by mhallendal** [comment]
@CalvHobbes preferably your backend service should combine the various sources into one full view model (this avoids the extra round trips as well). However if this is not possible another solution would be to have `A` (from above example) return a view model containing _place holders_ which will be read and replaced by `B`, `C` and `D`.

As an example with some _meta-JSON_.
```
...
{
  "id": "banner_1",
  "group": "placeholder_banner",
  "metadata": {
    "banner_component_uri": "https://..."
  }
},
{
  "id": "story_1",
  "group": "placeholder_story",
  "metadata": {
    "story_component_uri": "https://..."
  }
},
{
  "id": "banner_2",
  "group": "placeholder_banner",
  "metadata": {
    "story_component_uri": "https://..."
  }
}
...
```

`B`, `C` and `D` can go through the components in the view model they get from previous step and find all components of a specific type through `enumerateAllComponentModelBuildersWithBlock:`. I used the `group` property to categories the placeholders so that `B`, `C` and `D` can filter on that to decide which to act on. The data needed to process each particular place holder can then be put in the component model (in this case in the `metadata` property) for each place holder. 

Once `B` (for example) have retrieved the data for each banner it simply _replaces_ the placeholder with a banner component with the downloaded data instead. Once the data is retrieved, use `-builderExistsForBodyComponentModelWithIdentifier:` to first make sure that the placeholder exists (using the `id` from the placeholder component) in the view model builder and then `builderForBodyComponentModelWithIdentifier:`. Once you have the _component model builder_, populate it with the downloaded data.

The result of running `B` would then be something like:
```
{                                               {
  "id": "banner_1",                               "id": "banner_1",
  "group": "placeholder_banner",            =>    "group": "banner",
  "metadata": {                                   "component": {
    "banner_component_uri": "https://..."           "id": "default: banner",
  }                                                 "category": "banner",
}                                                 },
                                                  "text": {
                                                    "title": "Banner Title"
                                                  }
                                                }
```

And just to make clear, a single instance of `B` would then be responsible for replacing _all_ `placeholder_banner`.

**Comment by CalvHobbes** [comment]
Hi @mhallendal , this is an interesting example and I can see how this would work, especially if the component's data is coming in the JSON as well. If the data was available in the JSON for all components, I could have just used the built-in features to loadJSON (which would load corresponding widgets in the specified order, with the specified data). 
In your example above, I could have the first operation fetch the JSON and define what components need to be added. However, it would be unwieldy for my content operation factory to return an array of all the operations that can possibly exist in the feature being registered (it could be all the operations I define application-wide). Let's say that was a small set and I could write my operation factory that way, I could have operation "B" look for all banner components and add them via the viewmodelbuilder, however, it can't manage the ordering (banner->story->banner in the example above - so the "StoryOperation" needs to add its component before the BannerOperation adds the 2nd Banner component).  If that were doable somehow, then the next challenge I have is how to set up action observers etc. for each instance. If a single instance of operation B is setting up multiple Banner components, it has to be coded to handle actions from all these instances. If it has to asynchronously fetch data for the component from a service (and then invoke contentOperationRequiresRescheduling), it has to ensure that the data is added to the correct component etc. Not technically impossible, but it does become a little more complicated. In my use case, we will likely have a larger majority of components (and corresponding operations) that need to get data asynchronously from a service , as opposed to components for which I can get data directly from the initial JSON. This is the reason why, for these type of components, we'd like to write each Operation to have the ability to manage a single "functional component". This is probably rather convoluted, and like I said before, I suspect that we're using HUBFramework in a slightly "deviant" fashion :)

**Comment by mhallendal** [comment]
@CalvHobbes For the ordering that's not a problem since you will be replacing the placeholders (which are in the order you want the end result). That means the order of which your content operations are defined doesn't matter, they will all just replace the placeholders in place.

The state keeping of each component an unfortunate drawback on how content operations are designed. Off the top of my head you could store them in a dictionary from component id (`banner_1`) to the data needed to populate it. In your render method you replace all placeholders which exist in the dictionary. When any of your fetch operations finishes you simply add the data to the dictionary and call `contentOperationRequiresRescheduling`.

I imagine the problem could be if you have a huge number of content operations and components in which case it might end up being a performance issue to go through all components each content operation.

All this said, I'm currently working on a change that will make the view model loader and content operations optional (as in, you can write any loading mechanism you like outside of the framework). After that you should be able to design a solution that fits you better, the only think that matters is that you at the end get a `viewModel` to feed to the `HUBViewController`.

**Comment by CalvHobbes** [comment]
@mhallendal that sounds like a useful change - more than allowing a different loading mechanism, if your change allows us to do the loading asynchronously, that would be fantastic (that is the crux of the problem above since the operation factory has to "commit" to a specific set of operation instances instead of being allowed to asynchronously). Is this going to be a breaking change, and do you have a sense of when this change will be available?

**Comment by mhallendal** [comment]
@CalvHobbes I'm pretty sure you can do what you want with the current solution as described above. My change will not change how the view model builder (or content operations) work. However you will be able to have more control of the content operations (and can for example create a completely new view model loader based on the data downloaded from the backend).

Just to make sure you understood what I meant. Here is a diagram of what I had in mind:

```
PH: B = Placeholder: Banner
PH: C = Placeholder: Story
                                                                                     
 A loads the page layout                                                             
                                                                                     
                                                                                     
         PH: B           PH: B            PH: B           Spinner                    
         PH: S           PH: S            PH: S           Spinner  ┌────────────────┐
 ┌─────┐ PH: B ┌─────┐   PH: B  ┌─────┐   PH: B  ┌─────┐  Spinner  │                │
 │  A  │──────▶│  B  │─────────▶│  C  │─────────▶│  D  │──────────▶│   Rendering    │
 └─────┘       └─────┘          └─────┘          └─────┘           │                │
                                                                   └────────────────┘
                                                                                     
                                                                                     
   B finishes loading first banner                                                   
                                                                                     
          Banner           Banner           Banner                                   
          PH: S            PH: S            Spinner  ┌────────────────┐              
 ┌─────┐  PH: B   ┌─────┐  PH: B   ┌─────┐  Spinner  │                │              
 │  B  │─────────▶│  C  │─────────▶│  D  │──────────▶│   Rendering    │              
 └─────┘          └─────┘          └─────┘           │                │              
                                                     └────────────────┘              
                                                                                     
                                                                                     
  C finishes loading story                                                           
                                                                                     
                          Banner           Banner                                    
                          Story            Story    ┌────────────────┐               
                 ┌─────┐  PH: B   ┌─────┐  Spinner  │                │               
                 │  C  │─────────▶│  D  │──────────▶│   Rendering    │               
                 └─────┘          └─────┘           │                │               
                                                    └────────────────┘               
                                                                                     
 B finishes loading second banner                                                    
                                                                                     
         Banner           Banner           Banner                                    
         PH: S            Story            Story    ┌────────────────┐               
┌─────┐  Banner  ┌─────┐  Banner  ┌─────┐  Banner   │                │               
│  B  │─────────▶│  C  │─────────▶│  D  │──────────▶│   Rendering    │               
└─────┘          └─────┘          └─────┘           │                │               
                                                    └────────────────┘               
```

I added a content operation `D` at the end that simply replaces any placeholders with a spinner to indicate that part of the view isn't loaded yet.

The change I'm working on shouldn't be breaking anything and will optional. However, if you want to make use of the change you need to update your code.

**Comment by CalvHobbes** [comment]
@mhallendal thank you for the diagram, it helps tremendously. I'll chew over this for a bit. Thanks for all your help! I look forward to seeing the changes you mention.

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
