### ISSUE TITLE
HUBComponentWrapper reuse edge case?

### ISSUE THREAD

**Issue by mumme** [spotify/HubFramework#284]
When a `HUBComponentWrapper` gets reused, it carries its old model. If the new model is identical to the old one set on the reused wrapper, `prepareViewForReuse` and `configureViewWithModel:containerViewSize` never get called.

**Comment by mumme** [comment]
My current workaround is to always set a timestamp on the `metadata` of the new component `viewModel` generated by a content operation.

**Comment by mumme** [comment]
This is my component model: 

```
    {
      "id": "toogle-option",
      "component": { "id": "stats:segmentedControl", "category": "row" },
      "target": { "actions": "select-content" },
      "metadata": { "selected-content":"toogle-option-1" },
      "children": [
        { "component": { "id": "content-selector" },
          "id": "toogle-option-1",
          "text": { "title": "Option 1" }
        },
        { "component": { "id": "content-selector" },
          "id": "toogle-option-2",
          "text": { "title": "Option 2" }
        },
      ]
    },
```

I toggle `"metadata": { "selected-content":"toogle-option-1" }` contents between 2 values.
This component is always on screen.

1. initial model is `"selected-content":"toogle-option-1"`.
2. changes to `"selected-content":"toogle-option-2"`. `toogle-option-1` wrapper gets added to the reuse pool.
3. then, when we change it back to `"selected-content":"toogle-option-1"`, hubs reuses the old `toogle-option-1` wrapper that has this same model generated on step 1. 
4. compares it with the new model, they are identical.
5. the view does not get `configureView:containerSize` call.

**Comment by Goos** [comment]
This is probably caused by the `cellForItemAtIndexPath:` returning a new instance of the cell for the updated model, instead of reusing the cell previously used for that index path. This would prevent the `prepareForReuse:`-calls propagating down to the wrapper, and adding it back to the reuse pool in time.

Could it be that this could be caused by `UICollectionView` update semantics? I'm thinking the updated model would trigger a call to `reloadItemsAtIndexPaths:`, which, in the UICollectionView world, is seen as a deletion followed by an insertion. 

Or perhaps it could be due to a new instance of `UICollectionViewLayoutAttributes` returned from the layout class for the updated item? I vaguely recall instance equality being important when animating insertions / deletions 🤔

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
