### ISSUE TITLE
Carthage support is currently not functional

### ISSUE THREAD

**Issue by eliperkins** [spotify/HubFramework#39]
Hey! Just wanted to start by saying thanks for open sourcing this! Been following @JohnSundell's talks about this and it's exciting to see the internals now. 🎉 

I went to go play around with this today, so I created a new Xcode project and dropped a Cartfile in, that contained only the following:

```gml
github "spotify/HubFramework" ~> 2.0
```

Upon running `carthage bootstrap`, I got the following result:

```bash
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Cloning HubFramework
*** Checking out HubFramework at "2.0.0"
*** xcodebuild output can be found in /var/folders/23/894nltqn68z80wshzlztjd20393j93/T/carthage-xcodebuild.JgNOeT.log
*** Skipped building HubFramework due to the error:
Dependency "HubFramework" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/spotify/HubFramework/issues/new
```

Looking at the schemes shared from the project, HubFramework is definitely a shared scheme... but it's a static library and not a dynamic framework, as Carthage will expect it to be.

Are there certain motivations around keeping it a static library and not a dynamic framework? If so, you might want to remove the Carthage install instructions, as I believe Carthage has no intention of supporting static libraries at the time being. If not, I can work on a pull request to create a dynamic framework target! Thanks!

**Comment by JohnSundell** [comment]
Thanks for highlighting this issue @eliperkins! We're currently building as a static library to support our internal build process, but @rastersize is working on a fix for Carthage! 👍

**Comment by eliperkins** [comment]
Awesome news! Thanks!

**Comment by rastersize** [comment]
Thanks for the report @eliperkins. It still possible to integrate using Carthage, although not as convenient as pure Carthage might be. Basically if you use it for just dependency resolution. Then you add the HubFramework Xcode project to your app by dragging and dropping it from `Carthage/Checkouts/HubFramework/`.

I’ll remove the shared Xcode scheme for now so that Carthage won’t halt on the error.

We plan to add some tooling to ease the maintenance burden of having two targets. After which we’ll also add a dynamic framework target and the Xcode scheme back. I’ve created #42 to track that effort.

Sorry for the inconvenience!

---

As to why it’s a static library and not dynamic framework. Internally we only link with static libraries. Partly because of the Spotify app having iOS 7 support. And partly because of the load time hit dynamic libraries incur on iOS versions before 9.3.

**Comment by eliperkins** [comment]
Yup yup! Sounds like a solid workaround for the time being. Thanks!

**Comment by rastersize** [comment]
PR: https://github.com/spotify/HubFramework/pull/45
