### ISSUE TITLE
Guides in Swift

### ISSUE THREAD

**Issue by anantthebiker** [spotify/HubFramework#79]
Although the demo is in Swift3, the guide and other code snippets in the documentation is in Objective-C. I am new to it. Is there any document or stating guide aimed @ Swift. 
Thanks,
Anant

**Comment by JohnSundell** [comment]
@anantthebiker It's a great suggestion! 👍 We currently don't have any guides that use Swift for sample code, as we use Objective-C internally at Spotify. We do want to support both though, so ideally there would be a switch inline in the guides to switch the sample code between Swift & Objective-C (just like the Apple docs do). It's not super trivial to pull off though, since the guides are basically a static HTML page generated from markdown.

If any web developer (my Javascript is lousy) wants to take a look and contribute to this we'd be super happy 😄

**Comment by rastersize** [comment]
Apart from the guides it’d also be nice if the API docs could be switched between Objective-C and Swift. To do that we depend on Jazzy adding support. Which is unfortunately not trivial according to https://github.com/realm/jazzy/issues/663 (their issue tracking such a feature request).

**Comment by JensAyton** [comment]
The Hub Framework is being phased out at Spotify, and therefore we will not be maintaining it further.
